### ISSUE TITLE
Model weights to GCP.

### ISSUE THREAD

**Issue by oke-aditya** [oke-aditya/fashion_intel#15]
First 2 are preferable.

- I will try to push weights to GCP bucket which are almost least cost.
- Just attach a `.sh` file so that people get these.

It should as simple as 

```
!wget <model_bukcet_url>
!wget <model_bukcet_url>
!wget <model_bukcet_url>
```

**Comment by oke-aditya** [comment]
Yeah, I have the Google Cloud link as public. Already tested with a txt file.
Do have a look [here](https://storage.googleapis.com/fashion-intel-models/fashion_.intel.txt)

We will bundle all these together in `.sh` file. Just models weights left to be shifted.

**Comment by ramaneswaran** [comment]
Yeah thats a good plan
I guess the model weights issue is resolved

**Comment by oke-aditya** [comment]
Shifted the weights to GCP. It is publicly accessible bucket. No issues here.
